### ISSUE TITLE
document API endpoints

### ISSUE THREAD

**Issue by Haroenv** [johnotander/random-a11y-api#1]
Right now it isn't easy as an outstander what's allowed. I see that `votes` has a `json` payload, and know that `stats` exist, but it seems useful to have an overview in for example the README that lists what endpoints exist, and if we're even supposed to use them in demos or sites.

**Comment by johno** [comment]
Thanks for creating this issue!

It's on my todo list to create formal documentation for the API (was waiting for it to stabilize before doing so). I expect a formal API with documentation to be released in the next week : ) I'll be sure to let you know when that happens 😎

**Comment by Haroenv** [comment]
Awesome, can't wait to use it when it's settled.

**Comment by johno** [comment]
Sorry about the delay, here we go!: http://randoma11y.com/#/api
